export const users = [
  {
    name: "Clifford Izuchukwu",
    email: "clifford@gmail.com",
    department: "IT",
    startDate: " hello",
    tasks: {
      SignNDA: true,
      submitId: true,
      setUpEmail: true,
      HrOrientation: true,
      companyTools: false,
      meetingWithManager: true,
    },
  },
  {
    name: "Clifford Izuchukwu",
    email: "clifford@gmail.com",
    department: "IT",
    startDate: " hello",
    tasks: {
      SignNDA: true,
      submitId: true,
      setUpEmail: true,
      HrOrientation: true,
      companyTools: true,
      meetingWithManager: true,
    },
  },
  {
    name: "Clifford Izuchukwu",
    email: "clifford@gmail.com",
    department: "IT",
    startDate: " hello",
    tasks: {
      SignNDA: true,
      submitId: true,
      setUpEmail: true,
      HrOrientation: true,
      companyTools: true,
      meetingWithManager: true,
    },
  },
  {
    name: "Clifford Izuchukwu",
    email: "clifford@gmail.com",
    department: "IT",
    startDate: " hello",
    tasks: {
      SignNDA: true,
      submitId: true,
      setUpEmail: true,
      HrOrientation: true,
      companyTools: true,
      meetingWithManager: true,
    },
  },
];
